# Generated by Django 6.0.1 on 2026-02-07 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_remove_manga_manga_manga_content_cbe7e1_idx_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vertical', models.BooleanField(default=True, verbose_name='Vertical Reading')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mangareadingsettings',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mangareadingsettings',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='mangareadingsettings',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='readinghistory',
            name='users_readi_user_id_e99579_idx',
        ),
        migrations.RemoveIndex(
            model_name='readinghistory',
            name='users_readi_user_id_e4d5eb_idx',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bookmark',
            name='users_bookm_user_id_636448_idx',
        ),
        migrations.RemoveIndex(
            model_name='readingprogress',
            name='users_readi_user_id_abd77c_idx',
        ),
        migrations.RenameField(
            model_name='readingprogress',
            old_name='chapter',
            new_name='last_chapter',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.CharField(choices=[('reading', 'Reading'), ('planned', 'Planned'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.manga'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MangaReadingSettings',
        ),
        migrations.RemoveField(
            model_name='readinghistory',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='readinghistory',
            name='manga',
        ),
        migrations.RemoveField(
            model_name='readinghistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='current_page',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='total_pages',
        ),
        migrations.DeleteModel(
            name='ReadingHistory',
        ),
    ]
