# Generated by Django 6.0.1 on 2026-02-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('default_orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('alternative_titles', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField()),
                ('original_url', models.URLField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total_chapters', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('bookmarks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mangas', to='manga.contenttype')),
                ('genres', models.ManyToManyField(blank=True, related_name='mangas', to='manga.genre')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField()),
                ('title', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField()),
                ('pages_count', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['slug'], name='manga_manga_slug_20a47e_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['-updated_at'], name='manga_manga_updated_82f022_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['content_type'], name='manga_manga_content_cbe7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['manga', '-number'], name='manga_chapt_manga_i_3d9a00_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('manga', 'number')},
        ),
    ]
