# Generated by Django 6.0.1 on 2026-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='volume',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
