# Generated by Django 6.0.1 on 2026-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_chapter_unique_together_chapterimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('manga', 'number')},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ChapterImage',
        ),
    ]
