# Generated by Django 6.0.1 on 2026-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_alter_chapter_unique_together_alter_chapter_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
