# Generated by Django 6.0.1 on 2026-02-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_alter_chapter_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='manga',
            name='manga_manga_content_cbe7e1_idx',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='status',
        ),
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
