# Generated by Django 6.0.1 on 2026-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_remove_manga_manga_manga_content_cbe7e1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='source',
            field=models.CharField(choices=[('senkuro', 'Senkuro'), ('mangalib', 'MangaLib'), ('mangahub', 'MangaHub'), ('other', 'Other')], db_index=True, default='senkuro', max_length=20),
        ),
    ]
