# Generated by Django 6.0.1 on 2026-02-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_manga_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='source',
            field=models.CharField(choices=[('senkuro', 'Senkuro'), ('mangalib', 'MangaLib'), ('mangahub', 'MangaHub'), ('other', 'Other')], db_index=True, default='senkuro', help_text='Источник манги', max_length=20),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['source', 'slug'], name='manga_manga_source_c6416d_idx'),
        ),
    ]
