# Generated by Django 6.0.1 on 2026-02-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0008_alter_manga_cover_url_alter_manga_source_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='manga',
            name='manga_manga_source_c6416d_idx',
        ),
        migrations.AlterField(
            model_name='manga',
            name='cover_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='manga',
            name='source',
            field=models.CharField(choices=[('senkuro', 'Senkuro'), ('mangalib', 'MangaLib'), ('mangahub', 'MangaHub'), ('other', 'Other')], db_index=True, default='senkuro', max_length=20),
        ),
    ]
